name: set-branch-protection

on:
  repository_dispatch:
    types: [new_repository_created]

jobs:
  protect-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Set branch protection
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.ORG_ADMIN_TOKEN}}
        script: |
          const org = context.payload.organization.login;
          const repo = context.payload.repository.name;
        
          console.log(`Setting protection for ${org}/${repo}`);
          await github.rest.repos.updateBranchProtection({
            owner: org,
            repo: repo,
            branch: 'main',
            required_status_checks: null,
            enforce_admins: true,
            required_pull_request_reviews: {
              required_approving_review_count: 1
            },
            restrictions: null
          });
        
