name: set-branch-protection

on:
    repository_dispatch:
        types: [repo-created]

jobs:
    protect-branch:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2        
        - name: Set branch protection
          run: |
            curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/branches/main/protection \
            -d '{
                "required_status_checks": null,
                "enforce_admins": true,
                "required_pull_request_reviews": {
                "dismissal_restrictions": {},
                "dismiss_stale_reviews": false,
                "require_code_owner_reviews": false,
                "required_approving_review_count": 1
                },
                "restrictions": null
            }'
            # - name: Set branch protection
            #   uses: actions/github-script@v6
            #   with:
            #     github-token: ${{secrets.ORG_ADMIN_TOKEN}}
            #     script: |
            #         await github.rest.repos.updateBranchProtection({
            #             owner: context.payload.organization.login,
            #             repo: context.payload.repository.name,
            #             branch: 'main',
            #             required_status_checks: null,
            #             enforce_admins: true,
            #             required_pull_request_reviews: {
            #               required_approving_review_count: 1
            #             },
            #             restrictions: null
            #           })