name: Create Issue in Another Repo

on:
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create issue in another repository
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        curl -X POST \
          -H "Authorization: token ${{ PAT_GITHUB }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/siddjos/notfy6/issues \
          -d '{"title":"New Issue created","body":"This is the body of the new issue created by GitHub Actions."}'
