name: Create Issue in Another Repo

on:
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clone the remote repository
      uses: actions/checkout@v2
      with:
        repository: siddjos/notfy6
        token: ${{ secrets.PAT_GITHUB }}
        path: notfy6

    - name: Ensure README1.md exists in the remote repository
      run: |
        cd notfy6
        if [ ! -f README1.md ]; then
          echo "# Project Title" > README1.md
          echo "This is the initial README file created by GitHub Actions." >> README1.md
          git config --global user.email "siddharth.joshi21@gmail.com"
          git config --global user.name "Siddharth Joshi"
          git add README1.md
          git commit -m "Create README1.md"
          git push origin main
        else
          echo "README1.md already exists."
        fi

    - name: Create issue in another repository
      env:
        GH_TOKEN: ${{ secrets.PAT_GITHUB }}
      run: |
        curl -X POST \
          -H "Authorization: token $GH_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/siddjos/notfy6/issues \
          -d '{"title":"New Issue created","body":"This is the body of the new issue created by GitHub Actions."}'
